<?php declare(strict_types=1);
return [
    'target_php_version' => null,
    'strict_param_checking' => true,
    'strict_property_checking' => true,
    'strict_return_checking' => true,
    'check_docblock_signature_return_type_match' => true,
    'check_docblock_signature_param_type_match' => true,
    'prefer_narrowed_phpdoc_param_type' => true,
    'prefer_narrowed_phpdoc_return_type' => true,
    'allow_method_param_type_widening' => false,
    'dead_code_detection' => true,
    'backward_compatibility_checks' => false,
    'quick_mode' => false,
    'analyze_signature_compatibility' => true,
    'minimum_severity' => 0,
    'allow_missing_properties' => false,
    'null_casts_as_any_type' => false,
    'null_casts_as_array' => false,
    'array_casts_as_null' => false,
    'scalar_implicit_cast' => false,
    'scalar_implicit_partial' => [],
    'ignore_undeclared_variables_in_global_scope' => false,
    'suppress_issue_types' => [
        'PhanUndeclaredClassMethod',
        'PhanUndeclaredProperty',
        'PhanUnreferencedPublicClassConstant',
        'PhanUndeclaredTypeParameter',
        'PhanUnusedPublicFinalMethodParameter',
        'PhanUndeclaredClassConstant',
        'PhanUnreferencedPublicMethod',
        'PhanUndeclaredTypeReturnType',
        'PhanTypeMismatchDeclaredReturn',
        'PhanUndeclaredClassInstanceof',
        'PhanTypeMismatchReturn',
        'PhanUndeclaredExtendedClass',
        'PhanUndeclaredInterface',
        'PhanUnreferencedProtectedProperty',
    ],
    'whitelist_issue_types' => [
        // 'PhanAccessMethodPrivate',
    ],
];
