git submodule add https://github.com/karaka-management/oms-Tools.git Modules/Tools
git submodule add https://github.com/karaka-management/oms-Tag.git Modules/Tag
git submodule add https://github.com/karaka-management/oms-Organization.git Modules/Organization
git submodule add https://github.com/karaka-management/oms-Editor.git Modules/Editor
git submodule add https://github.com/karaka-management/oms-Navigation.git Modules/Navigation
git submodule add https://github.com/karaka-management/oms-Auditor.git Modules/Auditor
git submodule add https://github.com/karaka-management/oms-News.git Modules/News
git submodule add https://github.com/karaka-management/oms-Knowledgebase.git Modules/Knowledgebase
git submodule add https://github.com/karaka-management/oms-Help.git Modules/Help
git submodule add https://github.com/karaka-management/oms-Helper.git Modules/Helper
git submodule add https://github.com/karaka-management/oms-Monitoring.git Modules/Monitoring
git submodule add https://github.com/karaka-management/oms-Tasks.git Modules/Tasks
git submodule add https://github.com/karaka-management/oms-Dashboard.git Modules/Dashboard
git submodule add https://github.com/karaka-management/oms-Profile.git Modules/Profile
git submodule add https://github.com/karaka-management/oms-Search.git Modules/Search
git submodule add https://github.com/karaka-management/oms-Calendar.git Modules/Calendar
git submodule add https://github.com/karaka-management/oms-Checklist.git Modules/Checklist
git submodule add https://github.com/karaka-management/oms-Kanban.git Modules/Kanban
git submodule add https://github.com/karaka-management/oms-MyPrivate.git Modules/MyPrivate
git submodule add https://github.com/karaka-management/oms-Marketing.git Modules/Marketing
git submodule add https://github.com/karaka-management/oms-EventManagement.git Modules/EventManagement
git submodule add https://github.com/karaka-management/oms-ProjectManagement.git Modules/ProjectManagement
git submodule add https://github.com/karaka-management/oms-RiskManagement.git Modules/RiskManagement
git submodule add https://github.com/karaka-management/oms-HumanResourceTimeRecording.git Modules/HumanResourceTimeRecording
git submodule add https://github.com/karaka-management/oms-HumanResourceManagement.git Modules/HumanResourceManagement
git submodule add https://github.com/karaka-management/oms-Workflow.git Modules/Workflow
git submodule add https://github.com/karaka-management/oms-Job.git Modules/Job